// Nguồn duy nhất cho nhãn action/resource trong toàn bộ frontend.
// Dùng bởi: audit-table, audit/page, activity-feed.

export const ACTION_LABELS: Record<string, string> = {
  create: 'Tạo mới',
  update: 'Cập nhật',
  delete: 'Xóa',
  list: 'Xem',
  view: 'Xem',
  login: 'Đăng nhập',
  logout: 'Đăng xuất',
  lock: 'Khóa tài khoản',
  unlock: 'Mở khóa tài khoản',
  reset_password: 'Đặt lại mật khẩu',
  change_password: 'Đổi mật khẩu',
  assign_roles: 'Gán vai trò',
  add_member: 'Thêm thành viên',
  remove_member: 'Xóa thành viên',
  transfer_user: 'Chuyển phòng ban',
  assign_dept_role: 'Gán chức vụ',
  upload: 'Tải lên',
  download: 'Tải xuống',
  preview: 'Xem trước',
  move: 'Di chuyển',
  move_bulk: 'Di chuyển hàng loạt',
  edit_content: 'Cập nhật phiên bản',
  edit_file: 'Cập nhật phiên bản',
  rename: 'Đổi tên',
  share: 'Chia sẻ',
  revoke: 'Thu hồi quyền truy cập',
  restore_version: 'Khôi phục phiên bản',
  delete_version: 'Xóa phiên bản',
  download_version: 'Tải phiên bản',
  re_extract: 'Số hóa lại',
  cancel_extract: 'Hủy số hóa',
  re_embed: 'Nhúng lại vector',
  cancel_embed: 'Hủy nhúng vector',
  re_embed_batch: 'Nhúng hàng loạt',
  update_role_permissions: 'Cập nhật quyền vai trò',
  create_public_link: 'Tạo liên kết công khai',
  update_public_link: 'Cập nhật liên kết công khai',
  revoke_public_link: 'Thu hồi liên kết',
  chat_query: 'Hỏi trợ lý AI',
  update_feedback: 'Đánh giá phản hồi',
  access_denied: 'Truy cập bị từ chối',
  export: 'Xuất file',
};

export const RESOURCE_LABELS: Record<string, string> = {
  users: 'Người dùng',
  documents: 'Tài liệu',
  folders: 'Thư mục',
  roles: 'Vai trò',
  departments: 'Phòng ban',
  permissions: 'Phân quyền',
  audit: 'Nhật ký hệ thống',
  auth: 'Xác thực',
  chat: 'Trò chuyện',
  chat_session: 'Trò chuyện',
  'resource-permissions': 'Phân quyền tài nguyên',
  'public-links': 'Liên kết công khai',
  glossary: 'Từ điển chuyên ngành',
  'ai-quality': 'Chất lượng AI',
  dashboard: 'Bảng điều khiển',
  profile: 'Hồ sơ cá nhân',
};

// Badge style cho cột Hành động trong bảng audit
export const ACTION_BADGE_STYLE: Record<string, { bg: string; text: string; dot: string }> = {
  create:                   { bg: 'bg-emerald-500/15 border border-emerald-500/30', text: 'text-emerald-600 dark:text-emerald-400', dot: 'bg-emerald-500' },
  upload:                   { bg: 'bg-emerald-500/15 border border-emerald-500/30', text: 'text-emerald-600 dark:text-emerald-400', dot: 'bg-emerald-500' },
  add_member:               { bg: 'bg-emerald-500/15 border border-emerald-500/30', text: 'text-emerald-600 dark:text-emerald-400', dot: 'bg-emerald-500' },
  create_public_link:       { bg: 'bg-emerald-500/15 border border-emerald-500/30', text: 'text-emerald-600 dark:text-emerald-400', dot: 'bg-emerald-500' },
  update:                   { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  edit_content:             { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  edit_file:                { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  assign_roles:             { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  assign_dept_role:         { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  update_role_permissions:  { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  update_public_link:       { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  delete:                   { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  remove_member:            { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  revoke:                   { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  revoke_public_link:       { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  cancel_extract:           { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  cancel_embed:             { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  delete_version:           { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  list:                     { bg: 'bg-violet-500/15 border border-violet-500/30', text: 'text-violet-600 dark:text-violet-400', dot: 'bg-violet-500' },
  view:                     { bg: 'bg-violet-500/15 border border-violet-500/30', text: 'text-violet-600 dark:text-violet-400', dot: 'bg-violet-500' },
  preview:                  { bg: 'bg-violet-500/15 border border-violet-500/30', text: 'text-violet-600 dark:text-violet-400', dot: 'bg-violet-500' },
  lock:                     { bg: 'bg-amber-500/15 border border-amber-500/30', text: 'text-amber-600 dark:text-amber-400', dot: 'bg-amber-500' },
  unlock:                   { bg: 'bg-amber-500/15 border border-amber-500/30', text: 'text-amber-600 dark:text-amber-400', dot: 'bg-amber-500' },
  reset_password:           { bg: 'bg-amber-500/15 border border-amber-500/30', text: 'text-amber-600 dark:text-amber-400', dot: 'bg-amber-500' },
  change_password:          { bg: 'bg-amber-500/15 border border-amber-500/30', text: 'text-amber-600 dark:text-amber-400', dot: 'bg-amber-500' },
  restore_version:          { bg: 'bg-amber-500/15 border border-amber-500/30', text: 'text-amber-600 dark:text-amber-400', dot: 'bg-amber-500' },
  login:                    { bg: 'bg-green-500/15 border border-green-500/30', text: 'text-green-600 dark:text-green-400', dot: 'bg-green-500' },
  logout:                   { bg: 'bg-orange-500/15 border border-orange-500/30', text: 'text-orange-600 dark:text-orange-400', dot: 'bg-orange-500' },
  move:                     { bg: 'bg-teal-500/15 border border-teal-500/30', text: 'text-teal-600 dark:text-teal-400', dot: 'bg-teal-500' },
  move_bulk:                { bg: 'bg-teal-500/15 border border-teal-500/30', text: 'text-teal-600 dark:text-teal-400', dot: 'bg-teal-500' },
  transfer_user:            { bg: 'bg-teal-500/15 border border-teal-500/30', text: 'text-teal-600 dark:text-teal-400', dot: 'bg-teal-500' },
  rename:                   { bg: 'bg-blue-500/15 border border-blue-500/30', text: 'text-blue-600 dark:text-blue-400', dot: 'bg-blue-500' },
  access_denied:            { bg: 'bg-rose-500/15 border border-rose-500/30', text: 'text-rose-600 dark:text-rose-400', dot: 'bg-rose-500' },
  share:                    { bg: 'bg-indigo-500/15 border border-indigo-500/30', text: 'text-indigo-600 dark:text-indigo-400', dot: 'bg-indigo-500' },
  download:                 { bg: 'bg-cyan-500/15 border border-cyan-500/30', text: 'text-cyan-600 dark:text-cyan-400', dot: 'bg-cyan-500' },
  download_version:         { bg: 'bg-cyan-500/15 border border-cyan-500/30', text: 'text-cyan-600 dark:text-cyan-400', dot: 'bg-cyan-500' },
  re_extract:               { bg: 'bg-cyan-500/15 border border-cyan-500/30', text: 'text-cyan-600 dark:text-cyan-400', dot: 'bg-cyan-500' },
  re_embed:                 { bg: 'bg-cyan-500/15 border border-cyan-500/30', text: 'text-cyan-600 dark:text-cyan-400', dot: 'bg-cyan-500' },
  re_embed_batch:           { bg: 'bg-cyan-500/15 border border-cyan-500/30', text: 'text-cyan-600 dark:text-cyan-400', dot: 'bg-cyan-500' },
  chat_query:               { bg: 'bg-sky-500/15 border border-sky-500/30', text: 'text-sky-600 dark:text-sky-400', dot: 'bg-sky-500' },
  update_feedback:          { bg: 'bg-sky-500/15 border border-sky-500/30', text: 'text-sky-600 dark:text-sky-400', dot: 'bg-sky-500' },
  export:                   { bg: 'bg-cyan-500/15 border border-cyan-500/30', text: 'text-cyan-600 dark:text-cyan-400', dot: 'bg-cyan-500' },
};

// Màu chữ cho cột Tài nguyên trong bảng audit
export const RESOURCE_COLORS: Record<string, string> = {
  users: 'text-blue-600 dark:text-blue-400',
  documents: 'text-amber-600 dark:text-amber-400',
  folders: 'text-yellow-600 dark:text-yellow-400',
  roles: 'text-purple-600 dark:text-purple-400',
  departments: 'text-indigo-600 dark:text-indigo-400',
  permissions: 'text-rose-600 dark:text-rose-400',
  audit: 'text-slate-600 dark:text-slate-400',
  auth: 'text-green-600 dark:text-green-400',
  chat: 'text-sky-600 dark:text-sky-400',
  chat_session: 'text-sky-600 dark:text-sky-400',
  'resource-permissions': 'text-orange-600 dark:text-orange-400',
  'public-links': 'text-teal-600 dark:text-teal-400',
  glossary: 'text-lime-600 dark:text-lime-400',
  'ai-quality': 'text-pink-600 dark:text-pink-400',
  dashboard: 'text-slate-600 dark:text-slate-400',
  profile: 'text-violet-600 dark:text-violet-400',
};
