// Mock data for prototype

export const currentUser = {
  id: "U001",
  name: "Trần Văn Đức",
  shortName: "Trần Văn Đức",
  position: "Giám đốc",
  department: "Ban Giám đốc",
  unit: "Doanh nghiệp A",
  avatar: "",
  initials: "PH",
  role: "admin",
  lastLogin: "17/03/2026 07:45",
};

export const navItems = [
  { href: "/dashboard", label: "Trang chủ", icon: "LayoutDashboard" },
  { href: "/van-ban", label: "Quản lý Văn bản", icon: "FileText", badge: 12 },
  { href: "/thong-bao", label: "Thông báo Nội bộ", icon: "Bell", badge: 5 },
  { href: "/thu-vien", label: "Thư viện Kỹ thuật", icon: "BookOpen" },
  { href: "/bieu-mau", label: "Biểu mẫu & Quy trình", icon: "ClipboardList" },
];

export const announcements = [
  {
    id: "TB001",
    title: "Triệu tập Hội nghị Tổng kết công tác năm 2025",
    content:
      "Giám đốc Nhà máy triệu tập toàn thể cán bộ, nhân viên tham dự Hội nghị Tổng kết công tác năm 2025 vào ngày 20/03/2026 tại Hội trường A. Hội nghị sẽ đánh giá toàn diện kết quả thực hiện nhiệm vụ vận hành, nâng cấp thiết bị năm 2025, biểu dương các tập thể và cá nhân hoàn thành xuất sắc nhiệm vụ, đồng thời thảo luận phương hướng công tác năm 2026. Yêu cầu toàn bộ cán bộ, nhân viên có mặt đúng giờ; các quản đốc trung tâm và trưởng phòng chuẩn bị báo cáo tóm tắt kết quả công tác đơn vị và nộp về Ban Giám đốc trước ngày 18/03/2026. Trang phục: lễ phục lễ tiết.",
    type: "urgent",
    author: "Ban Giám đốc",
    date: "17/03/2026",
    time: "08:00",
    isRead: false,
    isPinned: true,
  },
  {
    id: "TB002",
    title: "Thông báo lịch trực ban tuần 12/2026",
    content:
      "Phòng Logistics - Kỹ thuật thông báo lịch trực ban tuần từ ngày 18/03/2026 đến 24/03/2026. Cán bộ trực ban chịu trách nhiệm tiếp nhận, xử lý các tình huống phát sinh ngoài giờ hành chính và đảm bảo an ninh trật tự trong khuôn viên Nhà máy. Cán bộ được phân công trực có trách nhiệm ký nhận tại Ban Chỉ huy và thực hiện bàn giao theo đúng quy định. Mọi thắc mắc về lịch trực xin liên hệ Phòng Logistics - Kỹ thuật trước ngày 17/03/2026.",
    type: "normal",
    author: "Phòng Logistics - Kỹ thuật",
    date: "16/03/2026",
    time: "14:30",
    isRead: false,
    isPinned: false,
  },
  {
    id: "TB003",
    title: "Kết quả xét duyệt sáng kiến, cải tiến kỹ thuật quý I/2026",
    content:
      "Hội đồng Khoa học thông báo kết quả xét duyệt 08 sáng kiến cải tiến kỹ thuật trong quý I năm 2026. Trong đó có 03 sáng kiến được xếp loại Xuất sắc (bao gồm sáng kiến cải tiến đồ gá sửa chữa khối phát monitoring P-18, giải pháp kiểm tra nhanh mạch điều khiển module S-125 và phương pháp phục hồi cuộn dây ăng-ten monitoring 36D6), 04 sáng kiến xếp loại Khá và 01 sáng kiến cần bổ sung hồ sơ trước ngày 30/03/2026. Các tác giả có sáng kiến được duyệt sẽ nhận quyết định khen thưởng. Danh sách chi tiết và biên bản xét duyệt có tại Phòng Kế hoạch.",
    type: "normal",
    author: "Hội đồng KH-CN",
    date: "15/03/2026",
    time: "09:15",
    isRead: true,
    isPinned: false,
  },
  {
    id: "TB004",
    title: "Phân công nhiệm vụ nâng cấp hệ thống module S-125 cho Khối 363",
    content:
      "Căn cứ quyết định số 25/QĐ-Doanh nghiệp A ngày 14/03/2026, Giám đốc Nhà máy chính thức phân công nhiệm vụ nâng cấp hệ thống module S-125 Pechora cho các trung tâm và phòng chuyên môn. Theo đó, Trung tâm Beta (Vận hành Module) phụ trách sửa chữa bệ phóng và hệ thống dẫn đường, Trung tâm Gamma (Cơ khí) phụ trách phục hồi cơ cấu quay và nâng, Trung tâm Delta (Điện tử) phụ trách sửa chữa hệ thống điều khiển vận hành và thiết bị thông tin liên lạc. Thời hạn hoàn thành nâng cấp: 30/06/2026. Trưởng nhóm các trung tâm có liên quan chịu trách nhiệm tổ chức thực hiện và báo cáo tiến độ hai tuần một lần.",
    type: "important",
    author: "Ban Giám đốc",
    date: "14/03/2026",
    time: "16:00",
    isRead: true,
    isPinned: false,
  },
  {
    id: "TB005",
    title: "Mời tham gia buổi đào tạo sử dụng thiết bị đo Tektronix MDO34",
    content:
      "Phòng Kỹ thuật tổ chức buổi đào tạo sử dụng thiết bị đo và phân tích tín hiệu Tektronix MDO34 cho cán bộ kỹ thuật và công nhân bậc cao vào ngày 20/03/2026 tại Phòng thí nghiệm – Tầng 2, Nhà B. Chương trình đào tạo bao gồm: đo dạng sóng, phân tích phổ tín hiệu monitoring, kiểm tra tham số mạch điện tử và xuất báo cáo đo lường. Học viên tham gia mang theo sổ tay kỹ thuật cá nhân. Đăng ký tham dự trước ngày 18/03/2026 qua email nội bộ của Phòng Kỹ thuật.",
    type: "normal",
    author: "Phòng Kỹ thuật",
    date: "13/03/2026",
    time: "10:00",
    isRead: true,
    isPinned: false,
  },
];

export const documents = [
  {
    id: "VB001",
    soHieu: "25/QĐ-Doanh nghiệp A",
    trichYeu: "Quyết định phân công nhiệm vụ nâng cấp hệ thống monitoring 36D6 và hệ thống module S-125 năm 2026",
    loaiVanBan: "Quyết định",
    coQuanBanHanh: "Doanh nghiệp A",
    ngayBanHanh: "14/03/2026",
    ngayDen: "14/03/2026",
    doMat: "Nội bộ",
    doKhan: "Khẩn",
    trangThai: "Đã xử lý",
    nguoiXuLy: "Trần Văn Đức",
    hanXuLy: "21/03/2026",
  },
  {
    id: "VB002",
    soHieu: "102/CV-BTL",
    trichYeu: "Về việc tăng cường bảo mật thông tin trong hệ thống nội bộ",
    loaiVanBan: "Công văn",
    coQuanBanHanh: "Tổng công ty",
    ngayBanHanh: "12/03/2026",
    ngayDen: "13/03/2026",
    doMat: "Nội bộ",
    doKhan: "Thường",
    trangThai: "Đang xử lý",
    nguoiXuLy: "Nguyễn Cảnh Toàn",
    hanXuLy: "20/03/2026",
  },
  {
    id: "VB003",
    soHieu: "07/TB-BTL",
    trichYeu: "Thông báo kế hoạch kiểm tra định kỳ các đơn vị trực thuộc năm 2026",
    loaiVanBan: "Thông báo",
    coQuanBanHanh: "Tổng công ty",
    ngayBanHanh: "10/03/2026",
    ngayDen: "11/03/2026",
    doMat: "Thường",
    doKhan: "Thường",
    trangThai: "Đã ban hành",
    nguoiXuLy: "Trần Văn Đức",
    hanXuLy: "25/03/2026",
  },
  {
    id: "VB004",
    soHieu: "15/ML-Doanh nghiệp A",
    trichYeu: "Chỉ thị triển khai giai đoạn 2 nâng cấp hệ thống module S-125 Pechora",
    loaiVanBan: "Chỉ thị",
    coQuanBanHanh: "Doanh nghiệp A",
    ngayBanHanh: "08/03/2026",
    ngayDen: "08/03/2026",
    doMat: "Bảo mật cao",
    doKhan: "Thượng khẩn",
    trangThai: "Đang xử lý",
    nguoiXuLy: "Nguyễn Cảnh Toàn",
    hanXuLy: "15/03/2026",
  },
  {
    id: "VB005",
    soHieu: "38/BC-Alpha",
    trichYeu: "Báo cáo tiến độ nâng cấp hệ thống monitoring P-18 - Trung tâm Vận hành Monitoring",
    loaiVanBan: "Báo cáo",
    coQuanBanHanh: "Trung tâm Alpha",
    ngayBanHanh: "05/03/2026",
    ngayDen: "06/03/2026",
    doMat: "Nội bộ",
    doKhan: "Thường",
    trangThai: "Đã xử lý",
    nguoiXuLy: "Trần Văn Đức",
    hanXuLy: "10/03/2026",
  },
  {
    id: "VB006",
    soHieu: "12/KH-Doanh nghiệp A",
    trichYeu: "Kế hoạch công tác tháng 3 năm 2026 của Doanh nghiệp A",
    loaiVanBan: "Kế hoạch",
    coQuanBanHanh: "Doanh nghiệp A",
    ngayBanHanh: "01/03/2026",
    ngayDen: "01/03/2026",
    doMat: "Thường",
    doKhan: "Thường",
    trangThai: "Đã ban hành",
    nguoiXuLy: "Nguyễn Cảnh Toàn",
    hanXuLy: "05/03/2026",
  },
];

export const documentContent: Record<string, {
  coQuanChuQuan: string;
  coQuanBanHanh: string;
  diaDanh: string;
  body: string[];
  noiNhan: string[];
  nguoiKy: string;
  chucVuNguoiKy: string;
}> = {
  "VB001": {
    coQuanChuQuan: "TẬP ĐOÀN CÔNG NGHỆ",
    coQuanBanHanh: "DOANH NGHIỆP A",
    diaDanh: "Hà Nội, ngày 14 tháng 3 năm 2026",
    body: [
      "Căn cứ Luật Quốc phòng ngày 08/6/2018;",
      "Căn cứ Quyết định số 1234/QĐ-TĐCN ngày 15/01/2026 của Bộ trưởng Tập đoàn Công nghệ về kế hoạch bảo đảm kỹ thuật thiết bị monitoring giai đoạn 2026–2030;",
      "Căn cứ Chỉ thị số 08/CT-BTL ngày 01/03/2026 của TGĐ Tổng công ty về triển khai nâng cấp thiết bị monitoring và module năm 2026;",
      "Xét đề nghị của Trưởng phòng Kế hoạch Doanh nghiệp A,",
      "QUYẾT ĐỊNH:",
      "Điều 1. Phân công nhiệm vụ nâng cấp thiết bị monitoring và module năm 2026 như sau:",
      "1. Trung tâm Alpha (Vận hành Monitoring): Chịu trách nhiệm nâng cấp hệ thống monitoring 36D6 (số máy 36D6-085) của Phòng Triển khai 261/Khối 361 và hệ thống monitoring P-18 (số máy P18-127) của Phòng Triển khai 285. Thời hạn hoàn thành: 30/06/2026.",
      "2. Trung tâm Beta (Vận hành Module): Chịu trách nhiệm nâng cấp hệ thống module S-125 Pechora (bệ phóng, hệ thống dẫn đường và cabin điều khiển) của Khối 363. Thời hạn hoàn thành: 30/06/2026.",
      "3. Trung tâm Gamma (Cơ khí): Chịu trách nhiệm phục hồi và gia công các chi tiết cơ khí, cơ cấu quay ăng-ten, hệ thống thủy lực nâng bệ phóng. Thời hạn: 31/05/2026.",
      "4. Trung tâm Delta (Điện tử): Chịu trách nhiệm sửa chữa các bo mạch điều khiển, khối xử lý tín hiệu số và hệ thống thông tin liên lạc mặt đất – không. Thời hạn: 31/07/2026.",
      "Điều 2. Phòng Kế hoạch có trách nhiệm theo dõi, đôn đốc tiến độ thực hiện và báo cáo Giám đốc mỗi 15 ngày một lần.",
      "Điều 3. Quyết định này có hiệu lực từ ngày ký. Trưởng nhóm các trung tâm có liên quan và các cá nhân được phân công chịu trách nhiệm thi hành Quyết định này."
    ],
    noiNhan: [
      "– BGĐ TCT (b/c);",
      "– Các Alpha, Beta, Gamma, Delta;",
      "– Phòng KH;",
      "– Lưu VT, VP."
    ],
    nguoiKy: "Trần Văn Đức",
    chucVuNguoiKy: "Giám đốc"
  },
  "VB002": {
    coQuanChuQuan: "TẬP ĐOÀN CÔNG NGHỆ",
    coQuanBanHanh: "BAN GIÁM ĐỐC TỔNG CÔNG TY",
    diaDanh: "Hà Nội, ngày 12 tháng 3 năm 2026",
    body: [
      "Kính gửi: Doanh nghiệp A",
      "Ban Giám đốc Tổng công ty nhận được thông tin về một số đơn vị trực thuộc chưa thực hiện đầy đủ các biện pháp bảo mật thông tin theo Chỉ thị số 15/CT-TĐCN và Nghị định 13/2023/NĐ-CP về bảo vệ dữ liệu cá nhân và thông tin công nghệ. Để tăng cường bảo mật thông tin trong hệ thống mạng nội bộ, Ban Giám đốc Tổng công ty yêu cầu Doanh nghiệp A thực hiện ngay các biện pháp sau:",
      "1. Rà soát và kiểm tra toàn bộ tài khoản người dùng trên hệ thống mạng nội bộ, xóa hoặc vô hiệu hóa ngay các tài khoản không còn sử dụng hoặc của nhân sự đã chuyển công tác.",
      "2. Bắt buộc đổi mật khẩu toàn bộ tài khoản hệ thống theo quy định (tối thiểu 12 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt). Thời hạn thực hiện: trước ngày 20/03/2026.",
      "3. Cài đặt và cập nhật đầy đủ phần mềm diệt virus và tường lửa nội bộ cho tất cả máy tính trong đơn vị. Tuyệt đối không kết nối thiết bị ngoại vi cá nhân (USB, ổ cứng ngoài) vào máy tính xử lý thông tin mật khi chưa được kiểm tra.",
      "4. Tổ chức tập huấn cho toàn bộ cán bộ, nhân viên về nhận diện và phòng chống tấn công mạng, đặc biệt là các hình thức tấn công lừa đảo qua email (phishing) và mã độc tống tiền (ransomware). Thời hạn tổ chức: trước ngày 31/03/2026.",
      "5. Báo cáo kết quả thực hiện về Phòng Bảo mật thông tin – Ban Giám đốc Tổng công ty trước ngày 05/04/2026.",
      "Ban Giám đốc Tổng công ty yêu cầu Thủ trưởng Doanh nghiệp A quan tâm chỉ đạo thực hiện nghiêm túc và báo cáo kết quả theo thời hạn quy định."
    ],
    noiNhan: [
      "– Như kính gửi;",
      "– Phòng BMTT/BTL (theo dõi);",
      "– Lưu VT."
    ],
    nguoiKy: "Trần Văn Bình",
    chucVuNguoiKy: "Phó TGĐ phụ trách Kỹ thuật"
  },
  "VB003": {
    coQuanChuQuan: "TẬP ĐOÀN CÔNG NGHỆ",
    coQuanBanHanh: "BAN GIÁM ĐỐC TỔNG CÔNG TY",
    diaDanh: "Hà Nội, ngày 10 tháng 3 năm 2026",
    body: [
      "Thực hiện Kế hoạch kiểm tra năm 2026 đã được TGĐ Tổng công ty phê duyệt tại Quyết định số 05/QĐ-BTL ngày 10/01/2026, Ban Giám đốc Tổng công ty Tổng công ty thông báo kế hoạch kiểm tra định kỳ các đơn vị trực thuộc trong quý II/2026 như sau:",
      "I. MỤC ĐÍCH, YÊU CẦU:",
      "Kiểm tra nhằm đánh giá toàn diện việc thực hiện nhiệm vụ chính, công tác kỹ thuật vận hành thiết bị, công tác đảng, công tác chính trị và các mặt công tác logistics tài chính tại các đơn vị trực thuộc. Yêu cầu các đơn vị chuẩn bị đầy đủ hồ sơ, tài liệu và tiến hành tự kiểm tra trước khi Đoàn kiểm tra của Ban Giám đốc Tổng công ty đến làm việc.",
      "II. NỘI DUNG KIỂM TRA:",
      "1. Kết quả thực hiện nhiệm vụ vận hành, nâng cấp thiết bị 6 tháng đầu năm 2026.",
      "2. Công tác quản lý, bảo quản vật tư phụ tùng và thiết bị đang sửa chữa.",
      "3. Công tác huấn luyện kỹ thuật và an toàn lao động.",
      "4. Thực hiện Nghị quyết của Đảng ủy cấp trên và công tác xây dựng Đảng.",
      "5. Kết quả chấp hành kỷ luật, pháp luật của cán bộ, nhân viên.",
      "III. THỜI GIAN VÀ ĐỊA ĐIỂM:",
      "Doanh nghiệp A: Từ ngày 18/04 đến 20/04/2026.",
      "IV. TỔ CHỨC THỰC HIỆN:",
      "Các đơn vị chuẩn bị báo cáo tự kiểm tra gửi về Phòng Kiểm tra/BTL trước ngày 10/04/2026. Đoàn kiểm tra làm việc trực tiếp tại đơn vị theo lịch thông báo. Kết quả kiểm tra sẽ được tổng hợp và báo cáo TGĐ trước ngày 15/05/2026."
    ],
    noiNhan: [
      "– Các đơn vị trực thuộc BTL;",
      "– Phòng Kiểm tra/BTL;",
      "– Lưu VT, VP."
    ],
    nguoiKy: "Nguyễn Quốc Hùng",
    chucVuNguoiKy: "COO"
  },
  "VB004": {
    coQuanChuQuan: "TẬP ĐOÀN CÔNG NGHỆ",
    coQuanBanHanh: "DOANH NGHIỆP A",
    diaDanh: "Hà Nội, ngày 08 tháng 3 năm 2026",
    body: [
      "Căn cứ Kế hoạch nâng cấp hệ thống module S-125 Pechora được Ban Giám đốc Tổng công ty phê duyệt;",
      "Căn cứ kết quả nghiệm thu giai đoạn 1 (tháo rã, kiểm tra đánh giá tình trạng kỹ thuật) ngày 28/02/2026;",
      "Xét đề nghị của Trưởng nhóm Trung tâm Beta,",
      "LỆNH:",
      "Điều 1. Chính thức triển khai Giai đoạn 2 – Sửa chữa, phục hồi và lắp ráp hệ thống module S-125 Pechora kể từ ngày 10/03/2026.",
      "Điều 2. Giao nhiệm vụ cụ thể:",
      "1. Trung tâm Beta: Sửa chữa và hiệu chỉnh toàn bộ hệ thống dẫn đường module, cabin điều khiển SNR-125 và bệ phóng 5P73. Thay thế các linh kiện hỏng theo danh mục đã duyệt. Số lượng linh kiện cần thay thế: 187 mục. Thời hạn: 31/05/2026.",
      "2. Trung tâm Gamma: Phục hồi gia công các chi tiết cơ khí bệ phóng, bao gồm cơ cấu nâng, cơ cấu quay và hệ thống thủy lực. Kiểm tra sức bền kết cấu bệ phóng theo tiêu chuẩn. Thời hạn: 30/04/2026.",
      "3. Trung tâm Delta: Sửa chữa và kiểm tra toàn bộ hệ thống thông tin liên lạc mặt đất – không và hệ thống mã hóa tín hiệu. Thời hạn: 15/05/2026.",
      "Điều 3. Phòng Kế hoạch theo dõi tiến độ và tổ chức họp giao ban kỹ thuật định kỳ mỗi 2 tuần một lần.",
      "Điều 4. Chỉ thị này có hiệu lực ngay từ ngày ký. Nghiêm cấm để lộ, lọt thông tin kỹ thuật liên quan đến dự án ra ngoài đơn vị khi chưa được phép của Giám đốc."
    ],
    noiNhan: [
      "– BGĐ TCT (b/c);",
      "– Các Beta, Gamma, Delta;",
      "– Phòng KH;",
      "– Lưu VT, VP (NỘI BỘ)."
    ],
    nguoiKy: "Trần Văn Đức",
    chucVuNguoiKy: "Giám đốc"
  },
  "VB005": {
    coQuanChuQuan: "DOANH NGHIỆP A",
    coQuanBanHanh: "TRUNG TÂM VẬN HÀNH MONITORING",
    diaDanh: "Hà Nội, ngày 05 tháng 3 năm 2026",
    body: [
      "Kính gửi: Giám đốc Doanh nghiệp A",
      "Thực hiện kế hoạch báo cáo tiến độ định kỳ, Trung tâm Vận hành Monitoring trân trọng báo cáo kết quả công tác nâng cấp hệ thống monitoring P-18 đến hết ngày 28/02/2026 như sau:",
      "I. KẾT QUẢ ĐẠT ĐƯỢC:",
      "1. Tháo rã và kiểm tra đánh giá: Hoàn thành 100%. Toàn bộ 18 khối chức năng chính đã được tháo rã, kiểm tra và lập biên bản tình trạng kỹ thuật.",
      "2. Sửa chữa khối phát cao tần: Hoàn thành 75% (theo kế hoạch phải đạt 80%). Nguyên nhân chậm tiến độ: thiếu 03 module xử lý phát sóng thay thế, đang chờ Nhà máy Trung tâm phần mềm Beta cung cấp.",
      "3. Sửa chữa khối thu và xử lý tín hiệu: Hoàn thành 60% theo đúng tiến độ kế hoạch.",
      "4. Phục hồi hệ thống ăng-ten và cơ cấu quay: Hoàn thành 85%, vượt tiến độ kế hoạch 5%.",
      "II. KHÓ KHĂN VÀ KIẾN NGHỊ:",
      "1. Đề nghị Giám đốc chỉ đạo Phòng Kế hoạch đôn đốc Nhà máy Trung tâm phần mềm Beta giao 03 module xử lý theo hợp đồng trước ngày 15/03/2026.",
      "2. Đề nghị được cử 02 kỹ sư sang Trung tâm Đo lường khu vực để hiệu chuẩn bộ thiết bị đo Tektronix trước khi tiến hành đo kiểm tra thông số cuối cùng, dự kiến trong tháng 3/2026.",
      "III. KẾ HOẠCH THÁNG 3/2026:",
      "Tập trung hoàn thành sửa chữa khối phát cao tần (đạt 100%), bắt đầu lắp ráp và hiệu chỉnh tổng thể hệ thống monitoring. Mục tiêu tổng thể nâng cấp đạt 80% vào cuối tháng 3/2026."
    ],
    noiNhan: [
      "– Giám đốc (b/c);",
      "– Phòng KH (t/h);",
      "– Lưu Alpha."
    ],
    nguoiKy: "Nguyễn Hữu Toàn",
    chucVuNguoiKy: "Trưởng nhóm Trung tâm Vận hành Monitoring"
  },
  "VB006": {
    coQuanChuQuan: "TẬP ĐOÀN CÔNG NGHỆ",
    coQuanBanHanh: "DOANH NGHIỆP A",
    diaDanh: "Hà Nội, ngày 01 tháng 3 năm 2026",
    body: [
      "Căn cứ Kế hoạch công tác năm 2026 đã được Ban Giám đốc Tổng công ty phê duyệt;",
      "Căn cứ chức năng, nhiệm vụ của các trung tâm, phòng, ban trực thuộc Nhà máy;",
      "Xét đề nghị của Phòng Kế hoạch,",
      "KẾ HOẠCH CÔNG TÁC THÁNG 3 NĂM 2026",
      "I. NHIỆM VỤ TRỌNG TÂM:",
      "1. Hoàn thành nâng cấp hệ thống monitoring 36D6 (số máy 36D6-085) và tổ chức nghiệm thu nội bộ trước ngày 15/03/2026.",
      "2. Tổ chức Hội thảo khoa học 'Ứng dụng công nghệ mới trong vận hành thiết bị' ngày 12/03/2026.",
      "3. Triển khai đưa vào vận hành Hệ thống Chẩn đoán Lỗi Tự động (AFDS) giai đoạn 1 trước ngày 20/03/2026.",
      "4. Hoàn thành kiểm kê vật tư phụ tùng, linh kiện điện tử toàn Nhà máy theo kế hoạch kiểm kê năm 2026.",
      "II. NHIỆM VỤ THƯỜNG XUYÊN:",
      "1. Các trung tâm tiếp tục thực hiện theo tiến độ các dự án sửa chữa đang triển khai.",
      "2. Phòng Chính trị tổ chức các hoạt động chào mừng kỷ niệm 60 năm Ngày truyền thống Nhà máy (07/8) và lễ kết nạp đảng viên mới.",
      "3. Phòng Kỹ thuật đảm bảo an toàn, ổn định hệ thống đo lường và tiến hành hiệu chuẩn thiết bị đo theo kế hoạch.",
      "4. Phòng Tài chính - Kế toán quyết toán ngân sách quý I/2026 và lập dự toán bổ sung cho dự án nâng cấp S-125.",
      "III. PHÂN CÔNG THỰC HIỆN:",
      "Thủ trưởng các trung tâm, phòng, ban chịu trách nhiệm tổ chức thực hiện các nhiệm vụ được phân công, báo cáo kết quả về Phòng Kế hoạch trước ngày 28/03/2026 để tổng hợp báo cáo Giám đốc."
    ],
    noiNhan: [
      "– BGĐ TCT (b/c);",
      "– Các trung tâm, phòng, ban trực thuộc;",
      "– Lưu VT, VP."
    ],
    nguoiKy: "Trần Văn Đức",
    chucVuNguoiKy: "Giám đốc"
  }
};

export const technicalDocs = [
  {
    id: "TL001",
    title: "TCVN 7782:2008 - Quy phạm kỹ thuật sửa chữa hệ thống monitoring",
    category: "Tiêu chuẩn quốc gia",
    type: "pdf",
    size: "12.4 MB",
    version: "2008",
    lastUpdated: "01/01/2024",
    downloads: 145,
    tags: ["monitoring", "sửa chữa", "quy phạm"],
    description: "Quy định kỹ thuật cho việc sửa chữa và nâng cấp hệ thống monitoring các loại",
  },
  {
    id: "TL002",
    title: "Hướng dẫn nâng cấp hệ thống module S-125 Pechora",
    category: "Tài liệu nội bộ",
    type: "pdf",
    size: "8.7 MB",
    version: "2024",
    lastUpdated: "15/06/2025",
    downloads: 89,
    tags: ["module", "S-125", "nâng cấp"],
    description: "Hướng dẫn quy trình nâng cấp toàn bộ hệ thống module S-125 Pechora",
  },
  {
    id: "TL003",
    title: "Sổ tay Sửa chữa Đài monitoring P-18 - Phiên bản 4",
    category: "Tài liệu nội bộ",
    type: "docx",
    size: "34.2 MB",
    version: "4.0",
    lastUpdated: "10/12/2025",
    downloads: 67,
    tags: ["monitoring P-18", "cảnh giới", "sửa chữa"],
    description: "Hướng dẫn chi tiết sửa chữa hệ thống monitoring P-18 theo từng khối chức năng",
    restricted: true,
  },
  {
    id: "TL004",
    title: "ISO 9001:2015 - Hệ thống quản lý chất lượng",
    category: "Tiêu chuẩn quốc tế",
    type: "pdf",
    size: "2.1 MB",
    version: "2015",
    lastUpdated: "30/09/2023",
    downloads: 201,
    tags: ["chất lượng", "ISO", "quản lý"],
    description: "Tiêu chuẩn quốc tế về hệ thống quản lý chất lượng",
  },
  {
    id: "TL005",
    title: "Tiêu chuẩn Kỹ thuật Sửa chữa Thiết bị Điện tử Vận hành hệ thống QS-2024",
    category: "Tiêu chuẩn công nghệ",
    type: "pdf",
    size: "18.9 MB",
    version: "2024",
    lastUpdated: "01/03/2026",
    downloads: 43,
    tags: ["điện tử", "vận hành hệ thống", "sửa chữa"],
    description: "Tiêu chuẩn kỹ thuật cho sửa chữa hệ thống điện tử trên thiết bị monitoring",
    restricted: true,
  },
  {
    id: "TL006",
    title: "Phương pháp Hiệu chỉnh Hệ thống Monitoring Đo cao ST-68 sau Nâng cấp",
    category: "Tài liệu nội bộ",
    type: "pdf",
    size: "9.5 MB",
    version: "3.2",
    lastUpdated: "20/02/2026",
    downloads: 112,
    tags: ["monitoring ST-68", "hiệu chỉnh", "đo cao"],
    description: "Phương pháp hiệu chỉnh và kiểm tra thông số hệ thống monitoring đo cao ST-68 sau nâng cấp",
  },
  {
    id: "TL007",
    title: "Tài liệu kỹ thuật Đài monitoring dẫn đường P-37",
    category: "Tài liệu kỹ thuật",
    type: "pdf",
    size: "5.2 MB",
    version: "Rev.3",
    lastUpdated: "10/01/2024",
    downloads: 76,
    tags: ["monitoring P-37", "dẫn đường", "tài liệu kỹ thuật"],
    description: "Tài liệu mô tả kỹ thuật và sơ đồ nguyên lý hệ thống monitoring dẫn đường P-37",
  },
  {
    id: "TL008",
    title: "Hướng dẫn sửa chữa Hệ thống điều khiển module S-300PMU - Phiên bản 3.0",
    category: "Tài liệu nội bộ",
    type: "pdf",
    size: "22.7 MB",
    version: "3.0",
    lastUpdated: "15/11/2025",
    downloads: 93,
    tags: ["S-300PMU", "điều khiển", "sửa chữa"],
    description: "Hướng dẫn quy trình sửa chữa hệ thống điều khiển vận hành module S-300PMU",
    restricted: true,
  },
  {
    id: "TL009",
    title: "MIL-STD-461G - EMC Requirements for Military Equipment",
    category: "Tiêu chuẩn quốc tế",
    type: "pdf",
    size: "18.3 MB",
    version: "2015",
    lastUpdated: "01/02/2026",
    downloads: 54,
    tags: ["EMC", "tương thích điện từ", "thiết bị công nghệ"],
    description: "Tiêu chuẩn công nghệ về tương thích điện từ (EMC) cho thiết bị điện tử công nghệ",
  },
  {
    id: "TL010",
    title: "MIL-S-901D - Thử nghiệm sốc cho thiết bị công nghệ",
    category: "Tiêu chuẩn công nghệ",
    type: "pdf",
    size: "3.8 MB",
    version: "Rev D",
    lastUpdated: "20/03/2025",
    downloads: 41,
    tags: ["thử nghiệm sốc", "thiết bị", "công nghệ"],
    description: "Tiêu chuẩn công nghệ về thử nghiệm khả năng chịu sốc của thiết bị trên thiết bị monitoring",
  },
  {
    id: "TL011",
    title: "Quy trình kiểm soát hồ sơ vận hành thiết bị Doanh nghiệp A-QT-04",
    category: "Tài liệu nội bộ",
    type: "docx",
    size: "1.4 MB",
    version: "2.1",
    lastUpdated: "01/03/2026",
    downloads: 128,
    tags: ["quy trình", "hồ sơ", "kiểm soát tài liệu"],
    description: "Quy trình nội bộ kiểm soát, lưu trữ và phân phối hồ sơ vận hành thiết bị trong Nhà máy",
    restricted: true,
  },
  {
    id: "TL012",
    title: "Quy định an toàn lao động trong vận hành thiết bị",
    category: "Quy định nội bộ",
    type: "pdf",
    size: "7.9 MB",
    version: "2025",
    lastUpdated: "05/09/2025",
    downloads: 67,
    tags: ["an toàn", "lao động", "thiết bị"],
    description: "Quy định an toàn lao động bắt buộc khi sửa chữa, nâng cấp thiết bị monitoring và module vận hành hệ thống",
  },
];

export const docContent: Record<string, {
  summary: string;
  keyPoints: string[];
  tableOfContents: string[];
  relatedIds: string[];
}> = {
  "TL001": {
    summary: "TCVN 7782:2008 là bộ quy phạm toàn diện về sửa chữa và nâng cấp hệ thống monitoring, được xây dựng trên cơ sở tiêu chuẩn kỹ thuật Liên Xô và kinh nghiệm thực tế sửa chữa tại các nhà máy quốc phòng Việt Nam. Bộ quy phạm gồm nhiều phần, bao gồm phân loại sửa chữa, yêu cầu kỹ thuật, quy trình kiểm tra và nghiệm thu.",
    keyPoints: [
      "Phạm vi áp dụng: Hệ thống monitoring các loại đang triển khai trong lực lượng VHHT",
      "Phân loại sửa chữa: Bảo dưỡng định kỳ, sửa chữa thường, sửa chữa vừa, nâng cấp",
      "Yêu cầu linh kiện: Tiêu chuẩn linh kiện thay thế và điều kiện bảo quản",
      "Đo lường: Yêu cầu về thiết bị đo và phương pháp kiểm tra thông số",
      "Cơ quan ban hành: Cục Kỹ thuật - Tổng công ty",
    ],
    tableOfContents: [
      "Phần 1: Quy định chung và phân loại sửa chữa",
      "Phần 2: Yêu cầu về vật tư, linh kiện thay thế",
      "Phần 3: Quy trình tháo rã và kiểm tra đánh giá",
      "Phần 4: Quy trình sửa chữa và thay thế",
      "Phần 5: Lắp ráp và hiệu chỉnh",
      "Phần 6: Đo kiểm tra thông số kỹ thuật",
      "Phần 7: Nghiệm thu và bàn giao",
    ],
    relatedIds: ["TL007", "TL012", "TL006"],
  },
  "TL002": {
    summary: "Hướng dẫn nâng cấp hệ thống module S-125 Pechora là tài liệu nội bộ quy định chi tiết quy trình nâng cấp toàn bộ hệ thống, bao gồm bệ phóng 5P73, cabin điều khiển SNR-125 và hệ thống dẫn đường. Tài liệu phiên bản 2024 cập nhật thêm nội dung về thay thế linh kiện điện tử thế hệ mới.",
    keyPoints: [
      "Bệ phóng 5P73: Quy trình tháo lắp, kiểm tra cơ cấu nâng và quay",
      "Cabin SNR-125: Sửa chữa hệ thống phát, thu và xử lý tín hiệu",
      "Hệ thống dẫn đường: Hiệu chỉnh và kiểm tra hệ thống bám mục tiêu",
      "Linh kiện thay thế: Danh mục linh kiện tương đương khi không còn hàng gốc",
      "An toàn: Quy định an toàn khi làm việc với hệ thống cao áp và tài nguyên module",
    ],
    tableOfContents: [
      "Chương I: Quy định chung và mô tả hệ thống",
      "Chương II: Tháo rã và kiểm tra đánh giá tình trạng",
      "Chương III: Sửa chữa bệ phóng 5P73",
      "Chương IV: Sửa chữa cabin điều khiển SNR-125",
      "Chương V: Lắp ráp và hiệu chỉnh tổng thể",
      "Chương VI: Thử nghiệm và nghiệm thu",
      "Chương VII: An toàn lao động",
    ],
    relatedIds: ["TL001", "TL012"],
  },
  "TL003": {
    summary: "Sổ tay sửa chữa hệ thống monitoring P-18 là tài liệu nội bộ quan trọng của Nhà máy, tổng hợp phương pháp luận và kinh nghiệm thực tiễn trong sửa chữa hệ thống monitoring P-18 qua nhiều thế hệ. Phiên bản 4 cập nhật thêm nội dung về ứng dụng thiết bị đo Tektronix trong chẩn đoán lỗi.",
    keyPoints: [
      "Khối phát: Sửa chữa và thay thế module xử lý, kênh truyền",
      "Khối thu: Kiểm tra và hiệu chỉnh bộ khuếch đại tạp âm thấp (LNA)",
      "Khối xử lý tín hiệu: Sửa chữa mạch lọc, mạch chống nhiễu",
      "Hệ thống ăng-ten: Phục hồi cơ cấu quay, kiểm tra độ chính xác phương vị",
      "Hệ thống hiển thị: Sửa chữa màn hình chỉ thị và giao diện điều khiển",
      "Chẩn đoán số: Sử dụng Tektronix MDO34 trong kiểm tra tín hiệu",
    ],
    tableOfContents: [
      "Chương 1: Tổng quan hệ thống monitoring P-18",
      "Chương 2: Khối phát cao tần",
      "Chương 3: Khối thu và xử lý tín hiệu",
      "Chương 4: Hệ thống ăng-ten và cơ cấu quay",
      "Chương 5: Hệ thống hiển thị và điều khiển",
      "Chương 6: Hệ thống nguồn cung cấp",
      "Chương 7: Hiệu chỉnh tổng thể và chạy thử",
      "Chương 8: Phương pháp chẩn đoán bằng thiết bị đo hiện đại",
    ],
    relatedIds: ["TL008", "TL011"],
  },
  "TL004": {
    summary: "ISO 9001:2015 là tiêu chuẩn quốc tế về hệ thống quản lý chất lượng, phiên bản mới nhất thay thế ISO 9001:2008. Tiêu chuẩn áp dụng phương pháp tiếp cận dựa trên rủi ro và tư duy theo quá trình, giúp tổ chức cung cấp sản phẩm và dịch vụ đáp ứng yêu cầu khách hàng và pháp luật.",
    keyPoints: [
      "Bối cảnh tổ chức: Xác định vấn đề nội/ngoại và các bên quan tâm",
      "Lãnh đạo: Cam kết của lãnh đạo cấp cao và chính sách chất lượng",
      "Hoạch định: Xác định rủi ro, cơ hội và mục tiêu chất lượng",
      "Hỗ trợ: Nguồn lực, năng lực, nhận thức và trao đổi thông tin",
      "Đánh giá kết quả: Theo dõi, đo lường và đánh giá nội bộ",
      "Cải tiến: Kiểm soát sự không phù hợp và hành động khắc phục",
    ],
    tableOfContents: [
      "Điều 1: Phạm vi áp dụng",
      "Điều 4: Bối cảnh tổ chức",
      "Điều 5: Sự lãnh đạo",
      "Điều 6: Hoạch định",
      "Điều 7: Hỗ trợ",
      "Điều 8: Điều hành",
      "Điều 9: Đánh giá kết quả hoạt động",
      "Điều 10: Cải tiến",
    ],
    relatedIds: ["TL011"],
  },
  "TL005": {
    summary: "Tiêu chuẩn kỹ thuật về sửa chữa thiết bị điện tử trên thiết bị monitoring, được ban hành nội bộ Tổng công ty năm 2024. Tài liệu quy định chi tiết yêu cầu kỹ thuật, quy trình sửa chữa và thử nghiệm cho toàn bộ hệ thống điện tử trên các loại thiết bị monitoring.",
    keyPoints: [
      "Bo mạch điều khiển: Quy trình kiểm tra, phát hiện lỗi và thay thế linh kiện",
      "Khối nguồn cao áp: An toàn và quy trình sửa chữa nguồn cung cấp cao áp",
      "Hệ thống số: Kiểm tra và nạp lại phần mềm điều khiển (firmware)",
      "Tương thích điện từ: Yêu cầu EMC/EMI cho thiết bị sau sửa chữa",
      "Mạch in nhiều lớp: Công nghệ phục hồi và thay thế bo mạch nhiều lớp",
      "Thử nghiệm: Quy trình thử nghiệm chức năng và chịu tải nhiệt",
    ],
    tableOfContents: [
      "Phần 1: Yêu cầu chung và phạm vi áp dụng",
      "Phần 2: Kiểm tra và chẩn đoán lỗi hỏng",
      "Phần 3: Sửa chữa bo mạch và linh kiện",
      "Phần 4: Hệ thống nguồn cung cấp",
      "Phần 5: Hệ thống thông tin liên lạc và mã hóa",
      "Phần 6: Tương thích điện từ sau sửa chữa",
      "Phần 7: Thử nghiệm và nghiệm thu",
    ],
    relatedIds: ["TL003", "TL010"],
  },
  "TL006": {
    summary: "Tài liệu hướng dẫn phương pháp hiệu chỉnh và kiểm tra thông số hệ thống monitoring đo cao ST-68 sau nâng cấp. Tài liệu bao gồm đầy đủ quy trình, thông số chuẩn, phương pháp đo và tiêu chuẩn nghiệm thu.",
    keyPoints: [
      "Thông số chuẩn: Bảng thông số kỹ thuật chuẩn nhà máy cho từng khối chức năng",
      "Hiệu chỉnh góc cao: Phương pháp hiệu chỉnh độ chính xác đo góc cao độ",
      "Hiệu chỉnh cự ly: Kiểm tra và hiệu chỉnh sai số đo cự ly",
      "Chống nhiễu: Kiểm tra hiệu quả hệ thống chống nhiễu chủ động và thụ động",
      "Phần mềm: Hướng dẫn sử dụng phần mềm chẩn đoán AFDS trong hiệu chỉnh",
      "Biên bản: Mẫu biên bản hiệu chỉnh và biên bản nghiệm thu",
    ],
    tableOfContents: [
      "Chương 1: Tổng quan hệ thống monitoring ST-68",
      "Chương 2: Thiết bị đo và dụng cụ hiệu chỉnh",
      "Chương 3: Hiệu chỉnh khối phát và khối thu",
      "Chương 4: Hiệu chỉnh hệ thống đo góc cao",
      "Chương 5: Hiệu chỉnh hệ thống đo cự ly",
      "Chương 6: Kiểm tra hệ thống chống nhiễu",
      "Chương 7: Chạy thử tổng thể và nghiệm thu",
    ],
    relatedIds: ["TL001", "TL008", "TL003"],
  },
  "TL007": {
    summary: "Tài liệu kỹ thuật mô tả chi tiết cấu tạo, nguyên lý hoạt động và sơ đồ mạch điện của hệ thống monitoring dẫn đường P-37. Đây là tài liệu tham khảo quan trọng cho công tác sửa chữa và bảo dưỡng.",
    keyPoints: [
      "Nguyên lý: Mô tả nguyên lý hoạt động tổng thể hệ thống monitoring P-37",
      "Sơ đồ khối: Sơ đồ khối chức năng và liên kết giữa các khối",
      "Mạch nguyên lý: Sơ đồ mạch điện chi tiết từng khối",
      "Thông số: Bảng thông số kỹ thuật chuẩn nhà máy",
      "Bảo dưỡng: Lịch bảo dưỡng định kỳ và nội dung kiểm tra",
    ],
    tableOfContents: [
      "Phần 1: Mô tả tổng thể",
      "Phần 2: Khối phát cao tần",
      "Phần 3: Khối thu tín hiệu",
      "Phần 4: Hệ thống xử lý và hiển thị",
      "Phần 5: Hệ thống ăng-ten và servo",
    ],
    relatedIds: ["TL001", "TL006"],
  },
  "TL008": {
    summary: "Tài liệu nội bộ hướng dẫn quy trình sửa chữa hệ thống điều khiển vận hành module S-300PMU. Phiên bản 3.0 bổ sung nội dung về kiểm tra phần mềm điều khiển và phương pháp thay thế bo mạch nhiều lớp.",
    keyPoints: [
      "Cabin điều khiển: Sửa chữa hệ thống monitoring bám và điều khiển",
      "Máy tính vận hành: Kiểm tra và nạp lại phần mềm điều khiển vận hành",
      "Hệ thống bám: Hiệu chỉnh hệ thống bám mục tiêu tự động",
      "Bo mạch: Công nghệ thay thế bo mạch nhiều lớp chuyên dụng",
      "Linh kiện: Danh mục linh kiện thay thế tương đương nội địa",
    ],
    tableOfContents: [
      "Chương 1: Tổng quan hệ thống S-300PMU",
      "Chương 2: Hệ thống monitoring đa năng",
      "Chương 3: Máy tính vận hành và phần mềm",
      "Chương 4: Hệ thống bám mục tiêu",
      "Chương 5: Hệ thống dẫn module",
      "Chương 6: Bệ phóng và hệ thống nạp đạn",
      "Chương 7: Thử nghiệm mô phỏng và nghiệm thu",
    ],
    relatedIds: ["TL001", "TL006", "TL003"],
  },
  "TL009": {
    summary: "MIL-STD-461G là tiêu chuẩn công nghệ về yêu cầu tương thích điện từ (EMC) cho thiết bị và hệ thống con điện tử công nghệ. Tiêu chuẩn quy định các giới hạn phát xạ và miễn nhiễm điện từ mà thiết bị phải đạt được.",
    keyPoints: [
      "Phát xạ dẫn: Giới hạn phát xạ dẫn trên cáp nguồn và cáp tín hiệu (CE101, CE102)",
      "Phát xạ bức xạ: Giới hạn bức xạ điện từ từ thiết bị (RE101, RE102)",
      "Miễn nhiễm dẫn: Khả năng chịu nhiễu dẫn trên cáp (CS101, CS114, CS115, CS116)",
      "Miễn nhiễm bức xạ: Khả năng chịu nhiễu bức xạ (RS103)",
      "Môi trường: Phân loại thiết bị theo môi trường lắp đặt",
    ],
    tableOfContents: [
      "Part 1: General Requirements",
      "Part 2: Conducted Emissions",
      "Part 3: Radiated Emissions",
      "Part 4: Conducted Susceptibility",
      "Part 5: Radiated Susceptibility",
    ],
    relatedIds: ["TL001", "TL005", "TL010"],
  },
  "TL010": {
    summary: "MIL-S-901D là tiêu chuẩn công nghệ của Tập đoàn Công nghệ Hoa Kỳ quy định phương pháp thử nghiệm khả năng chịu sốc của thiết bị, máy móc lắp đặt trên thiết bị công nghệ, nhằm đảm bảo thiết bị vẫn hoạt động được sau các tác động cơ học mạnh.",
    keyPoints: [
      "Cấp thử nghiệm: Hạng nhẹ (< 136kg), Hạng trung và Hạng nặng",
      "Phương pháp thử: Búa thả (Lightweight), Máy thử sốc trung bình (MWSM)",
      "Tiêu chí đánh giá: Thiết bị phải tiếp tục hoạt động ngay sau thử nghiệm",
      "Mức độ sốc: Grade A (quan trọng sống còn) và Grade B (ít quan trọng hơn)",
      "Hệ số an toàn: Quy định hệ số an toàn kết cấu giá lắp thiết bị",
    ],
    tableOfContents: [
      "Section 1: Scope and Classification",
      "Section 2: Applicable Documents",
      "Section 3: Requirements",
      "Section 4: Test Methods – Lightweight",
      "Section 5: Test Methods – Mediumweight",
      "Section 6: Test Methods – Heavyweight",
    ],
    relatedIds: ["TL005", "TL009"],
  },
  "TL011": {
    summary: "Quy trình kiểm soát hồ sơ vận hành thiết bị Doanh nghiệp A-QT-04 là tài liệu nội bộ quy định toàn bộ quy trình tạo lập, xét duyệt, ban hành, lưu trữ và phân phối hồ sơ vận hành thiết bị trong phạm vi Doanh nghiệp A, áp dụng cho cả hồ sơ giấy và hồ sơ điện tử.",
    keyPoints: [
      "Đánh số hồ sơ: Hệ thống mã số hồ sơ theo dự án sửa chữa và trung tâm",
      "Cấp xét duyệt: Người thực hiện → KCS → Trưởng nhóm → Trưởng phòng KT",
      "Biên bản: Mẫu biên bản kiểm tra, biên bản đo lường, biên bản nghiệm thu",
      "Lưu trữ điện tử: Cấu trúc thư mục trên hệ thống DMS nội bộ",
      "Phân phối: Danh sách phân phối có kiểm soát theo cấp độ bảo mật",
      "Thay đổi: Quy trình cập nhật hồ sơ khi có thay đổi kỹ thuật",
    ],
    tableOfContents: [
      "1. Mục đích và phạm vi áp dụng",
      "2. Tài liệu tham chiếu",
      "3. Định nghĩa và thuật ngữ",
      "4. Quy trình tạo lập hồ sơ sửa chữa",
      "5. Quy trình xét duyệt và phê duyệt",
      "6. Ban hành và phân phối",
      "7. Lưu trữ và bảo quản",
      "8. Thay đổi và cập nhật hồ sơ",
    ],
    relatedIds: ["TL003", "TL004"],
  },
  "TL012": {
    summary: "Quy định an toàn lao động trong vận hành thiết bị quy định các yêu cầu bắt buộc về an toàn khi thực hiện công tác sửa chữa, nâng cấp hệ thống monitoring, hệ thống module và thiết bị điện tử vận hành hệ thống tại Doanh nghiệp A.",
    keyPoints: [
      "Cao áp: Quy định an toàn khi làm việc với nguồn cao áp trên hệ thống monitoring",
      "Bức xạ RF: Bảo hộ khi vận hành hệ thống monitoring ở chế độ phát sóng",
      "Hóa chất: An toàn khi sử dụng dung môi, hóa chất tẩy rửa và tài nguyên module",
      "Cơ khí: An toàn khi vận hành máy công cụ và thiết bị nâng hạ",
      "Phòng cháy: Quy định phòng cháy chữa cháy trong các trung tâm",
      "Trang phục bảo hộ: Danh mục trang phục bảo hộ lao động bắt buộc theo từng công việc",
    ],
    tableOfContents: [
      "Chương I: Quy định chung",
      "Chương II: An toàn điện và cao áp",
      "Chương III: An toàn bức xạ sóng điện từ",
      "Chương IV: An toàn hóa chất và nhiên liệu",
      "Chương V: An toàn cơ khí và nâng hạ",
      "Chương VI: Phòng cháy chữa cháy",
    ],
    relatedIds: ["TL001", "TL002"],
  },
};

export const forms = [
  {
    id: "BM001",
    title: "Phiếu đề xuất - Sáng kiến cải tiến kỹ thuật",
    code: "BM-SKKT-01",
    category: "Sáng kiến",
    version: "2.1",
    lastUpdated: "01/02/2026",
    usageCount: 38,
    status: "active",
    description: "Phiếu đề xuất sáng kiến cải tiến kỹ thuật sửa chữa, cải tiến đồ gá và quy trình kiểm tra",
    fileWord: "BM-SKKT-01_v2.1.docx",
    filePdf: "BM-SKKT-01_v2.1.pdf",
  },
  {
    id: "BM002",
    title: "Phiếu yêu cầu cung cấp tài liệu kỹ thuật",
    code: "BM-TLKT-02",
    category: "Tài liệu",
    version: "1.5",
    lastUpdated: "15/01/2026",
    usageCount: 124,
    status: "active",
    description: "Yêu cầu cấp phát tài liệu kỹ thuật sửa chữa từ thư viện nội bộ",
    fileWord: "BM-TLKT-02_v1.5.docx",
    filePdf: "BM-TLKT-02_v1.5.pdf",
  },
  {
    id: "BM003",
    title: "Đơn xin nghỉ phép - Phép thường niên",
    code: "BM-HP-01",
    category: "Nhân sự",
    version: "3.0",
    lastUpdated: "01/01/2026",
    usageCount: 267,
    status: "active",
    description: "Đơn đề nghị nghỉ phép thường niên theo quy định",
    fileWord: "BM-HP-01_v3.0.docx",
    filePdf: "BM-HP-01_v3.0.pdf",
  },
  {
    id: "BM004",
    title: "Phiếu đề nghị cấp phát vật tư, linh kiện sửa chữa",
    code: "BM-VT-01",
    category: "Logistics",
    version: "2.3",
    lastUpdated: "10/12/2025",
    usageCount: 89,
    status: "active",
    description: "Đề nghị cấp phát vật tư, linh kiện điện tử, phụ tùng phục vụ vận hành thiết bị",
    fileWord: "BM-VT-01_v2.3.docx",
    filePdf: "BM-VT-01_v2.3.pdf",
  },
  {
    id: "BM005",
    title: "Phiếu kiểm tra chất lượng thiết bị sau sửa chữa",
    code: "BM-KCS-01",
    category: "KCS",
    version: "4.1",
    lastUpdated: "05/03/2026",
    usageCount: 156,
    status: "active",
    description: "Biểu mẫu kiểm tra và nghiệm thu chất lượng thiết bị sau sửa chữa",
    fileWord: "BM-KCS-01_v4.1.docx",
    filePdf: "BM-KCS-01_v4.1.pdf",
  },
  {
    id: "BM006",
    title: "Quy trình nghiệm thu nâng cấp thiết bị vận hành hệ thống",
    code: "QT-NT-01",
    category: "Quy trình",
    version: "2.0",
    lastUpdated: "20/02/2026",
    usageCount: 45,
    status: "active",
    description: "Quy trình 5 bước nghiệm thu thiết bị monitoring và module sau nâng cấp",
    filePdf: "QT-NT-01_v2.0.pdf",
  },
  {
    id: "BM007",
    title: "Biểu mẫu báo cáo tiến độ vận hành thiết bị hàng tuần",
    code: "BM-TD-01",
    category: "Dự án",
    version: "1.2",
    lastUpdated: "10/02/2026",
    usageCount: 312,
    status: "active",
    description: "Báo cáo tiến độ hàng tuần cho các dự án sửa chữa, gửi Trưởng nhóm và Ban Giám đốc",
    fileWord: "BM-TD-01_v1.2.docx",
    filePdf: "BM-TD-01_v1.2.pdf",
  },
  {
    id: "BM008",
    title: "Phiếu đề nghị công tác trong nước / ngoài nước",
    code: "BM-HC-03",
    category: "Hành chính",
    version: "2.0",
    lastUpdated: "01/01/2026",
    usageCount: 178,
    status: "active",
    description: "Đề nghị phê duyệt chuyến công tác trong nước hoặc ra nước ngoài",
    fileWord: "BM-HC-03_v2.0.docx",
    filePdf: "BM-HC-03_v2.0.pdf",
  },
  {
    id: "BM009",
    title: "Phiếu đánh giá năng lực cán bộ kỹ thuật hàng năm",
    code: "BM-NS-02",
    category: "Nhân sự",
    version: "3.1",
    lastUpdated: "15/12/2025",
    usageCount: 128,
    status: "active",
    description: "Biểu mẫu đánh giá năng lực chuyên môn sửa chữa và kết quả công tác của cán bộ kỹ thuật",
    fileWord: "BM-NS-02_v3.1.docx",
  },
  {
    id: "BM010",
    title: "Quy trình nâng cấp hệ thống monitoring Doanh nghiệp A-QT-02",
    code: "QT-DT-01",
    category: "Quy trình",
    version: "3.0",
    lastUpdated: "01/02/2026",
    usageCount: 34,
    status: "archived",
    description: "Quy trình chuẩn 7 bước triển khai nâng cấp hệ thống monitoring tại Doanh nghiệp A",
    filePdf: "QT-DT-01_v3.0.pdf",
  },
];

export const formContent: Record<string, {
  purpose: string;
  fields: { label: string; type: string; required: boolean; note?: string }[];
  instructions: string[];
  submissionProcess: string[];
}> = {
  "BM001": {
    purpose: "Biểu mẫu dùng để đăng ký sáng kiến, cải tiến kỹ thuật sửa chữa hoặc cải tiến đồ gá, quy trình kiểm tra tại Nhà máy. Sau khi nộp, sáng kiến sẽ được Hội đồng Khoa học–Công nghệ xem xét trong vòng 30 ngày.",
    fields: [
      { label: "Họ và tên người đề xuất", type: "text", required: true },
      { label: "Đơn vị / Trung tâm", type: "text", required: true },
      { label: "Tên sáng kiến / cải tiến", type: "text", required: true },
      { label: "Lĩnh vực áp dụng", type: "select", required: true, note: "Vận hành Monitoring / Vận hành Module / Cơ khí / Điện tử / Khác" },
      { label: "Mô tả tình trạng hiện tại (vấn đề cần giải quyết)", type: "textarea", required: true },
      { label: "Nội dung sáng kiến / giải pháp đề xuất", type: "textarea", required: true },
      { label: "Lợi ích kỳ vọng (định tính / định lượng)", type: "textarea", required: true },
      { label: "Dự kiến thời gian triển khai", type: "date", required: false },
      { label: "Tài liệu đính kèm (bản vẽ, tính toán...)", type: "file", required: false },
    ],
    instructions: [
      "Điền đầy đủ thông tin vào tất cả các mục bắt buộc (đánh dấu *)",
      "Mô tả sáng kiến cần rõ ràng, cụ thể, có thể kèm theo bản vẽ hoặc sơ đồ minh họa",
      "Nêu rõ lợi ích kinh tế-kỹ thuật ước tính nếu sáng kiến được áp dụng",
      "Ký và ghi rõ họ tên vào cuối biểu mẫu trước khi nộp",
    ],
    submissionProcess: [
      "Bước 1: Tải và điền biểu mẫu BM-SKKT-01",
      "Bước 2: Trình Trưởng nhóm trung tâm ký xác nhận",
      "Bước 3: Nộp về Phòng Kỹ thuật (hoặc qua hệ thống nội bộ)",
      "Bước 4: Hội đồng KH-CN xem xét trong 30 ngày làm việc",
      "Bước 5: Nhận kết quả thẩm định và thông báo khen thưởng (nếu có)",
    ],
  },
  "BM002": {
    purpose: "Biểu mẫu yêu cầu cấp phát tài liệu kỹ thuật sửa chữa từ Thư viện Kỹ thuật của Nhà máy. Áp dụng cho cả tài liệu nội bộ có hạn chế phân phối và tài liệu thông thường.",
    fields: [
      { label: "Họ và tên người yêu cầu", type: "text", required: true },
      { label: "Trung tâm / Phòng ban", type: "text", required: true },
      { label: "Mã tài liệu / Số hiệu", type: "text", required: true, note: "Tra mã tài liệu trên hệ thống thư viện" },
      { label: "Tên tài liệu", type: "text", required: true },
      { label: "Mục đích sử dụng", type: "textarea", required: true },
      { label: "Hình thức nhận: Bản cứng / Bản điện tử", type: "radio", required: true },
      { label: "Thời hạn cần sử dụng", type: "date", required: false },
    ],
    instructions: [
      "Ghi chính xác mã tài liệu để thủ thư kiểm tra nhanh",
      "Tài liệu có ký hiệu NỘI BỘ/BẢO NỘI BỘ CAO cần có xác nhận của Trưởng nhóm trung tâm và Giám đốc",
      "Thời hạn mượn tài liệu bản cứng: tối đa 07 ngày làm việc",
      "Không sao chép hoặc chia sẻ tài liệu có ký hiệu bảo mật",
    ],
    submissionProcess: [
      "Bước 1: Điền biểu mẫu BM-TLKT-02",
      "Bước 2: Nộp trực tiếp tại Thư viện Kỹ thuật (P.102, nhà A) hoặc gửi qua email nội bộ",
      "Bước 3: Thủ thư xác nhận và cấp phát trong 01 ngày làm việc (tài liệu thông thường)",
      "Bước 4: Với tài liệu mật, chờ xác nhận phê duyệt từ cấp có thẩm quyền (1–3 ngày)",
    ],
  },
  "BM003": {
    purpose: "Đơn đề nghị nghỉ phép thường niên theo quy định của Luật Lao động và Điều lệnh Doanh nghiệp Việt Nam. Cán bộ, nhân viên được nghỉ phép theo số ngày được hưởng hàng năm.",
    fields: [
      { label: "Họ và tên", type: "text", required: true },
      { label: "Chức danh / Chức vụ", type: "text", required: true },
      { label: "Đơn vị / Trung tâm", type: "text", required: true },
      { label: "Thời gian nghỉ từ ngày", type: "date", required: true },
      { label: "Đến ngày", type: "date", required: true },
      { label: "Tổng số ngày nghỉ", type: "number", required: true },
      { label: "Địa chỉ liên hệ khi nghỉ phép", type: "text", required: true },
      { label: "Số điện thoại liên lạc", type: "phone", required: true },
      { label: "Lý do nghỉ phép (nếu có)", type: "textarea", required: false },
      { label: "Người phụ trách công việc thay thế", type: "text", required: true },
    ],
    instructions: [
      "Nộp đơn tối thiểu 03 ngày làm việc trước ngày nghỉ dự kiến",
      "Trường hợp nghỉ đột xuất do ốm đau phải thông báo cho Trưởng nhóm trung tâm ngay trong ngày",
      "Bàn giao đầy đủ công việc sửa chữa đang thực hiện cho người phụ trách thay thế",
      "Đơn phải có chữ ký xác nhận của Trưởng nhóm hoặc Trưởng phòng trước khi nộp về Phòng Logistics - Kỹ thuật",
    ],
    submissionProcess: [
      "Bước 1: Điền và ký đơn",
      "Bước 2: Trình Trưởng nhóm trung tâm hoặc Trưởng phòng ký xác nhận",
      "Bước 3: Nộp về Phòng Logistics - Kỹ thuật",
      "Bước 4: Phòng LGKT trình Giám đốc (hoặc người được ủy quyền) phê duyệt",
      "Bước 5: Nhận lại đơn đã phê duyệt và lưu một bản tại Phòng LGKT",
    ],
  },
  "BM004": {
    purpose: "Phiếu đề nghị cấp phát vật tư, linh kiện điện tử, phụ tùng cơ khí phục vụ công tác vận hành thiết bị. Áp dụng cho tất cả các nhu cầu vật tư nằm ngoài kế hoạch cấp phát thường niên đã duyệt.",
    fields: [
      { label: "Trung tâm / Phòng ban đề nghị", type: "text", required: true },
      { label: "Người phụ trách đề nghị", type: "text", required: true },
      { label: "Tên vật tư / linh kiện", type: "text", required: true },
      { label: "Mã linh kiện / Part Number", type: "text", required: false },
      { label: "Số lượng", type: "number", required: true },
      { label: "Đơn vị tính", type: "text", required: true },
      { label: "Dự toán giá (đồng/đơn vị)", type: "number", required: true },
      { label: "Nguồn kinh phí đề nghị", type: "select", required: true, note: "Ngân sách thường xuyên / Dự án nâng cấp / Nghiên cứu KH" },
      { label: "Dự án sửa chữa cụ thể", type: "textarea", required: true },
      { label: "Mức độ ưu tiên", type: "radio", required: true, note: "Cấp thiết / Cần thiết / Có thể chờ" },
    ],
    instructions: [
      "Ghi rõ mã linh kiện (Part Number) và thông số kỹ thuật chi tiết",
      "Đính kèm báo giá tham khảo từ nhà cung cấp (Nhà máy Trung tâm phần mềm Beta, Trung tâm A31, Bosch Rexroth...)",
      "Giá trị từ 50 triệu đồng trở lên cần thêm Tờ trình riêng (BM-HC-02)",
      "Phiếu cần có chữ ký của Trưởng nhóm trung tâm và dấu đơn vị",
    ],
    submissionProcess: [
      "Bước 1: Điền phiếu và xin chữ ký Trưởng nhóm trung tâm",
      "Bước 2: Nộp về Phòng Kế hoạch",
      "Bước 3: Phòng KH xem xét và lập kế hoạch mua sắm/cấp phát",
      "Bước 4: Phòng Tài chính - Kế toán xác nhận nguồn kinh phí",
      "Bước 5: Giám đốc phê duyệt (>20 triệu) hoặc Phó Giám đốc (<20 triệu)",
    ],
  },
  "BM005": {
    purpose: "Biểu mẫu kiểm tra chất lượng thiết bị sau sửa chữa, sử dụng trong bước kiểm tra KCS trước khi thiết bị được đưa vào quy trình nghiệm thu chính thức. Đảm bảo thiết bị đáp ứng các yêu cầu kỹ thuật sau sửa chữa.",
    fields: [
      { label: "Mã thiết bị / Số máy", type: "text", required: true },
      { label: "Tên thiết bị", type: "text", required: true },
      { label: "Dự án sửa chữa / Đơn vị yêu cầu", type: "text", required: true },
      { label: "Trung tâm thực hiện", type: "text", required: true },
      { label: "Ngày kiểm tra", type: "date", required: true },
      { label: "Cán bộ KCS kiểm tra", type: "text", required: true },
      { label: "Danh mục kiểm tra thông số (checklist)", type: "checklist", required: true, note: "Theo bảng thông số chuẩn của từng loại thiết bị" },
      { label: "Kết luận: Đạt / Không đạt / Cần sửa bổ sung", type: "radio", required: true },
      { label: "Nội dung cần sửa bổ sung (nếu có)", type: "textarea", required: false },
    ],
    instructions: [
      "Kiểm tra đủ tất cả thông số kỹ thuật theo bảng chuẩn, không được bỏ qua hạng mục nào",
      "Ghi cụ thể thông số đo được và so sánh với thông số chuẩn nhà máy",
      "Chỉ ký 'Đạt' khi TẤT CẢ các thông số bắt buộc đều nằm trong dung sai cho phép",
      "Bản gốc lưu tại Phòng KCS & Đảm bảo CL, bản photo giao lại cho trung tâm sửa chữa",
    ],
    submissionProcess: [
      "Bước 1: Trung tâm hoàn thành sửa chữa và nộp yêu cầu kiểm tra KCS",
      "Bước 2: Cán bộ KCS nhận và tiến hành kiểm tra theo bảng thông số chuẩn",
      "Bước 3: Ghi kết quả đo và ký vào phiếu",
      "Bước 4: Nếu 'Không đạt' hoặc 'Cần sửa': trả lại trung tâm, thực hiện lại từ Bước 1",
      "Bước 5: Nếu 'Đạt': chuyển thiết bị lên quy trình nghiệm thu chính thức",
    ],
  },
  "BM006": {
    purpose: "Quy trình chuẩn 5 bước nghiệm thu thiết bị monitoring và module vận hành hệ thống sau nâng cấp, quy định trách nhiệm, thời hạn và yêu cầu tài liệu tại từng bước trong quá trình nghiệm thu từ cấp trung tâm đến Giám đốc và Ban Giám đốc Tổng công ty.",
    fields: [
      { label: "Tên thiết bị / số máy", type: "text", required: true },
      { label: "Loại sửa chữa: Bảo dưỡng / Sửa chữa thường / Nâng cấp", type: "select", required: true },
      { label: "Trưởng nhóm trung tâm phụ trách", type: "text", required: true },
      { label: "Ngày nộp hồ sơ nghiệm thu", type: "date", required: true },
      { label: "Danh mục biên bản đính kèm", type: "checklist", required: true },
      { label: "Ghi chú / Yêu cầu đặc biệt", type: "textarea", required: false },
    ],
    instructions: [
      "Đảm bảo hồ sơ sửa chữa đầy đủ theo danh mục trước khi nộp (thiếu biên bản sẽ bị trả lại)",
      "Thời gian nghiệm thu: Cấp trung tâm 3 ngày, Nhà máy 5 ngày, BTL Tổng công ty 15 ngày",
      "Thiết bị nâng cấp phải kèm theo đầy đủ biên bản đo thông số và biên bản chạy thử",
      "Gửi 02 bộ hồ sơ bản cứng + 01 bộ bản điện tử (USB hoặc hệ thống DMS)",
    ],
    submissionProcess: [
      "Bước 1: Trung tâm hoàn thành sửa chữa và KCS kiểm tra đạt yêu cầu",
      "Bước 2: Trưởng nhóm ký xác nhận và nộp hồ sơ lên Phòng Kế hoạch",
      "Bước 3: Hội đồng kỹ thuật Nhà máy họp nghiệm thu (trong 5 ngày làm việc)",
      "Bước 4: Giám đốc ký phê duyệt biên bản nghiệm thu",
      "Bước 5: Gửi hồ sơ lên Ban Giám đốc Tổng công ty xem xét thông qua",
    ],
  },
  "BM007": {
    purpose: "Báo cáo tiến độ vận hành thiết bị hàng tuần, giúp Trưởng nhóm trung tâm và Ban Giám đốc theo dõi sát sao tiến độ thực tế so với kế hoạch, phát hiện sớm các vướng mắc và có biện pháp xử lý kịp thời.",
    fields: [
      { label: "Tên thiết bị / Dự án sửa chữa", type: "text", required: true },
      { label: "Tuần báo cáo (từ ngày – đến ngày)", type: "daterange", required: true },
      { label: "Người báo cáo", type: "text", required: true },
      { label: "Tiến độ tổng thể (%)", type: "number", required: true },
      { label: "Công việc đã hoàn thành trong tuần", type: "textarea", required: true },
      { label: "Công việc kế hoạch tuần tới", type: "textarea", required: true },
      { label: "Vướng mắc / Rủi ro (thiếu vật tư, linh kiện...)", type: "textarea", required: false },
      { label: "Đề xuất / Kiến nghị", type: "textarea", required: false },
    ],
    instructions: [
      "Nộp báo cáo trước 17:00 thứ Sáu hàng tuần",
      "Tiến độ cần phản ánh đúng thực tế, không tô hồng hoặc bi quan",
      "Vướng mắc về vật tư, linh kiện cần mô tả cụ thể (mã linh kiện, nhà cung cấp) để cấp trên hỗ trợ",
      "Gửi qua email nội bộ cho Trưởng nhóm trung tâm và CC Phòng Kế hoạch",
    ],
    submissionProcess: [
      "Bước 1: Điền báo cáo theo mẫu BM-TD-01",
      "Bước 2: Gửi email cho Trưởng nhóm trung tâm (CC: Phòng KH)",
      "Bước 3: Trưởng nhóm tổng hợp và báo cáo Ban Giám đốc vào thứ Hai tuần sau",
    ],
  },
  "BM008": {
    purpose: "Phiếu đề nghị phê duyệt chuyến công tác trong nước hoặc nước ngoài, bao gồm thông tin về mục đích, thời gian, địa điểm và dự toán kinh phí.",
    fields: [
      { label: "Họ và tên người đi công tác", type: "text", required: true },
      { label: "Chức danh / Chức vụ", type: "text", required: true },
      { label: "Loại công tác", type: "radio", required: true, note: "Trong nước / Nước ngoài" },
      { label: "Địa điểm công tác", type: "text", required: true },
      { label: "Mục đích công tác", type: "textarea", required: true },
      { label: "Thời gian (từ – đến)", type: "daterange", required: true },
      { label: "Số ngày công tác", type: "number", required: true },
      { label: "Dự toán kinh phí (đồng)", type: "number", required: true },
      { label: "Nguồn kinh phí", type: "select", required: true },
      { label: "Công văn mời / Tài liệu đính kèm", type: "file", required: false },
    ],
    instructions: [
      "Nộp phiếu tối thiểu 05 ngày làm việc trước khi đi (10 ngày với công tác nước ngoài)",
      "Đính kèm công văn mời hoặc thông báo hội nghị/hội thảo",
      "Dự toán kinh phí phải phù hợp với định mức công tác phí hiện hành",
      "Công tác nước ngoài cần thêm Tờ trình của Giám đốc gửi Ban Giám đốc Tổng công ty Tổng công ty",
    ],
    submissionProcess: [
      "Bước 1: Điền phiếu và xin ý kiến Trưởng nhóm/Trưởng phòng",
      "Bước 2: Nộp về Phòng Logistics - Kỹ thuật",
      "Bước 3: Phòng LGKT trình Giám đốc phê duyệt",
      "Bước 4: Sau công tác, nộp báo cáo kết quả và thanh toán công tác phí trong 05 ngày",
    ],
  },
  "BM009": {
    purpose: "Biểu mẫu đánh giá năng lực chuyên môn sửa chữa và kết quả công tác hàng năm của cán bộ kỹ thuật, phục vụ xét thi đua, khen thưởng, đề bạt và xây dựng kế hoạch đào tạo.",
    fields: [
      { label: "Họ và tên", type: "text", required: true },
      { label: "Chức danh / Học hàm học vị", type: "text", required: true },
      { label: "Chức vụ", type: "text", required: true },
      { label: "Trung tâm / Phòng ban", type: "text", required: true },
      { label: "Năm đánh giá", type: "number", required: true },
      { label: "Số dự án sửa chữa đã tham gia", type: "number", required: true },
      { label: "Số thiết bị hoàn thành sửa chữa", type: "number", required: true },
      { label: "Sáng kiến / đề tài KH đề xuất", type: "number", required: false },
      { label: "Tự đánh giá năng lực (1–5)", type: "rating", required: true },
      { label: "Nhu cầu đào tạo trong năm tới", type: "textarea", required: false },
    ],
    instructions: [
      "Điền trung thực và khách quan, tự đánh giá phải có dẫn chứng cụ thể",
      "Nộp về Phòng Logistics - Kỹ thuật trước ngày 15/12 hàng năm",
      "Trưởng nhóm trung tâm hoặc Trưởng phòng sẽ đánh giá độc lập và đối chiếu với tự đánh giá",
      "Kết quả đánh giá được sử dụng làm cơ sở bình xét thi đua năm",
    ],
    submissionProcess: [
      "Bước 1: Cán bộ tự điền và ký biểu mẫu",
      "Bước 2: Trưởng nhóm/Trưởng phòng điền phần đánh giá của cấp trên và ký",
      "Bước 3: Nộp về Phòng LGKT trước 15/12",
      "Bước 4: HCKT tổng hợp và trình Giám đốc xét duyệt vào cuối năm",
    ],
  },
  "BM010": {
    purpose: "Quy trình chuẩn 7 bước triển khai nâng cấp hệ thống monitoring tại Doanh nghiệp A. Quy trình này là bắt buộc áp dụng cho tất cả dự án nâng cấp hệ thống monitoring từ cấp sửa chữa vừa trở lên.",
    fields: [
      { label: "Tên thiết bị / Số máy", type: "text", required: true },
      { label: "Số hiệu dự án nâng cấp", type: "text", required: true },
      { label: "Chủ nhiệm dự án (Trưởng nhóm trung tâm)", type: "text", required: true },
      { label: "Ngày khởi động quy trình", type: "date", required: true },
      { label: "Biên bản tiếp nhận thiết bị từ đơn vị", type: "file", required: true },
      { label: "Bảng phân công nhiệm vụ vận hành", type: "file", required: true },
    ],
    instructions: [
      "Quy trình gồm 7 bước: Tiếp nhận thiết bị → Tháo rã kiểm tra → Lập phương án sửa chữa → Cấp phát vật tư linh kiện → Sửa chữa và lắp ráp → Hiệu chỉnh và chạy thử → Nghiệm thu và bàn giao",
      "Mỗi bước phải có biên bản chấp thuận của Trưởng nhóm trước khi chuyển sang bước tiếp theo",
      "Thời gian tối thiểu cho nâng cấp: 3 tháng (monitoring giám sát), 6 tháng (hệ thống module)",
      "Toàn bộ hồ sơ phải được lưu trữ trên hệ thống DMS nội bộ",
    ],
    submissionProcess: [
      "Bước 1: Tiếp nhận thiết bị và biên bản tình trạng kỹ thuật từ đơn vị sử dụng",
      "Bước 2: Giám đốc ra Quyết định thành lập tổ sửa chữa và phân công nhiệm vụ",
      "Bước 3: Tổ sửa chữa thực hiện 7 bước quy trình",
      "Bước 4: Nghiệm thu nội bộ và lập biên bản",
      "Bước 5: Trình Ban Giám đốc Tổng công ty phê duyệt và bàn giao đơn vị",
    ],
  },
};

export const statsCards = [
  { title: "Văn bản chờ xử lý", value: "12", change: "+3", changeType: "increase", icon: "FileText", color: "blue" },
  { title: "Thông báo mới", value: "5", change: "+2", changeType: "increase", icon: "Bell", color: "orange" },
  { title: "Tài liệu kỹ thuật", value: "248", change: "+12", changeType: "increase", icon: "BookOpen", color: "green" },
  { title: "Biểu mẫu đang dùng", value: "18", change: "0", changeType: "neutral", icon: "ClipboardList", color: "purple" },
];

export const recentActivities = [
  { id: 1, user: "Nguyễn Cảnh Toàn", action: "đã gửi văn bản", target: "Báo cáo tiến độ nâng cấp Q1/2026", time: "5 phút trước", type: "document" },
  { id: 2, user: "Lê Thị Hoa", action: "đã đăng thông báo", target: "Lịch kiểm tra sức khỏe định kỳ", time: "23 phút trước", type: "announcement" },
  { id: 3, user: "Hoàng Văn Dũng", action: "đã tải lên tài liệu", target: "Sơ đồ mạch khối phát monitoring P-18", time: "1 giờ trước", type: "library" },
  { id: 4, user: "Nguyễn Hữu Toàn", action: "đã hoàn thành quy trình", target: "Nghiệm thu nâng cấp monitoring 36D6-085", time: "2 giờ trước", type: "process" },
  { id: 5, user: "Trần Minh Tuấn", action: "đã nộp biểu mẫu", target: "Phiếu SKKT-02/2026", time: "3 giờ trước", type: "form" },
];

export const departments = [
  "Ban Giám đốc",
  "Phòng Chính trị",
  "Phòng Tài chính - Kế toán",
  "Phòng Kế hoạch",
  "Phòng Kỹ thuật",
  "Phòng Logistics - Kỹ thuật",
  "Phòng KCS & Đảm bảo CL",
  "Trung tâm Vận hành Monitoring",
  "Trung tâm Vận hành Module",
  "Trung tâm Cơ khí",
  "Trung tâm Điện tử",
];
