import type { YeuCau } from '../../types';

export const danhSachYeuCau: YeuCau[] = [
  {
    id: 'YC-2026-001', donVi: 'DV-001',
    thietBi: 'Khối phát hệ thống monitoring TX-18 Terek',
    maThietBi: 'DTD-RA18-361-01',
    mucDich: 'Kiểm tra định kỳ', uuTien: 'cao',
    ngayGui: '2026-03-10', ngayHen: '2026-03-28',
    trangThai: 'da_tiep_nhan',
    nguoiGui: 'Nguyễn Văn An',
    phongLab: 'Phòng Lab Tín hiệu - Truyền dẫn',
    ghiChu: 'Kiểm tra tham số phát, tần số trung tâm, công suất phát xung của khối phát thiết bị monitoring TX-18.',
  },
  {
    id: 'YC-2026-002', donVi: 'DV-003',
    thietBi: 'Cụm cảm biến rung động cooling fan rack server SV-171',
    maThietBi: 'DTD-RD-927-05',
    mucDich: 'Kiểm tra phục vụ bảo trì', uuTien: 'trung_binh',
    ngayGui: '2026-03-12', ngayHen: '2026-04-15',
    trangThai: 'moi_tao',
    nguoiGui: 'Trần Quốc Bảo',
    phongLab: 'Phòng Lab Rung động',
    ghiChu: '',
  },
  {
    id: 'YC-2026-003', donVi: 'DV-004',
    thietBi: 'Hệ thống làm mát data center DC-300 số 02 — module thủy lực bơm tuần hoàn',
    maThietBi: 'DTD-BP300-367-02',
    mucDich: 'Xác minh sai lệch kỹ thuật', uuTien: 'khan_cap',
    ngayGui: '2026-03-15', ngayHen: '2026-03-22',
    trangThai: 'dang_do',
    nguoiGui: 'Lê Minh Cường',
    phongLab: 'Phòng Lab Áp suất',
    ghiChu: 'Phát hiện sai lệch áp suất thủy lực bơm tuần hoàn, cần xác minh gấp phục vụ vận hành SLA.',
  },
  {
    id: 'YC-2026-004', donVi: 'DV-002',
    thietBi: 'Bộ nguồn cao áp module điều khiển hệ thống SA-6 Kub',
    maThietBi: 'DTD-NC-921-07',
    mucDich: 'Đánh giá sau bảo trì', uuTien: 'cao',
    ngayGui: '2026-03-08', ngayHen: '2026-03-25',
    trangThai: 'cho_phe_duyet',
    nguoiGui: 'Phạm Hữu Đức',
    phongLab: 'Phòng Lab Điện-Điện tử',
    ghiChu: 'Bộ nguồn vừa thay 3 module công suất, cần đánh giá lại toàn bộ tham số đầu ra.',
  },
  {
    id: 'YC-2026-005', donVi: 'DV-006',
    thietBi: 'Kênh thu tín hiệu hệ thống monitoring 36D6 Tin Shield',
    maThietBi: 'DTD-KT-026-03',
    mucDich: 'Kiểm tra định kỳ', uuTien: 'trung_binh',
    ngayGui: '2026-02-20', ngayHen: '2026-03-15',
    trangThai: 'hoan_thanh',
    nguoiGui: 'Vũ Thế Anh',
    phongLab: 'Phòng Lab Tín hiệu - Truyền dẫn',
    ghiChu: '',
  },
  {
    id: 'YC-2026-006', donVi: 'DV-005',
    thietBi: 'Hệ thống cấp nguồn UPS server SV-30 — bơm & van điều áp',
    maThietBi: 'DTD-NL-935-11',
    mucDich: 'Đánh giá sau bảo trì', uuTien: 'cao',
    ngayGui: '2026-03-18', ngayHen: '2026-03-30',
    trangThai: 'da_tiep_nhan',
    nguoiGui: 'Hoàng Đình Giang',
    phongLab: 'Phòng Lab Lưu lượng',
    ghiChu: 'Hệ thống vừa thay bơm cao áp, cần kiểm tra lưu lượng & áp suất trước khi đưa vào vận hành.',
  },
  {
    id: 'YC-2026-007', donVi: 'DV-008',
    thietBi: 'Module điều khiển dẫn truyền dữ liệu KH-29 — khối xử lý tín hiệu',
    maThietBi: 'DTD-DD-291-04',
    mucDich: 'Đo kiểm nghiệm thu', uuTien: 'khan_cap',
    ngayGui: '2026-03-20', ngayHen: '2026-03-26',
    trangThai: 'dang_do',
    nguoiGui: 'Ngô Văn Hải',
    phongLab: 'Phòng Lab Điện-Điện tử',
    ghiChu: 'Nghiệm thu lô module mới nhập, ưu tiên xử lý phục vụ kiểm tra kỹ thuật toàn Doanh nghiệp A.',
  },
  {
    id: 'YC-2026-008', donVi: 'DV-007',
    thietBi: 'Cụm cân tải trọng linh kiện gắn trên giá đỡ rack server Ka-28',
    maThietBi: 'DTD-CT-375-02',
    mucDich: 'Kiểm tra định kỳ', uuTien: 'thap',
    ngayGui: '2026-01-15', ngayHen: '2026-02-10',
    trangThai: 'hoan_thanh',
    nguoiGui: 'Đỗ Quang Khải',
    phongLab: 'Phòng Lab Khối lượng-Hình học',
    ghiChu: '',
  },
  {
    id: 'YC-2026-009', donVi: 'DV-001',
    thietBi: 'Hệ thống làm mát module SA-3 Goa — cụm cảm biến nhiệt',
    maThietBi: 'DTD-LM-361-09',
    mucDich: 'Kiểm tra phục vụ bảo trì', uuTien: 'trung_binh',
    ngayGui: '2026-03-22', ngayHen: '2026-04-10',
    trangThai: 'moi_tao',
    nguoiGui: 'Bùi Thanh Long',
    phongLab: 'Phòng Lab Nhiệt-Quang',
    ghiChu: '',
  },
  {
    id: 'YC-2026-010', donVi: 'DV-002',
    thietBi: 'Hệ thống monitoring đầu cuối server SV-30 N001VE Bars — khối thu phát tín hiệu',
    maThietBi: 'DTD-RD-921-12',
    mucDich: 'Xác minh sai lệch kỹ thuật', uuTien: 'cao',
    ngayGui: '2026-03-19', ngayHen: '2026-03-29',
    trangThai: 'tu_choi',
    nguoiGui: 'Phạm Hữu Đức',
    phongLab: 'Phòng Lab Tín hiệu - Truyền dẫn',
    ghiChu: 'Không đủ điều kiện đo: khối thu phát cần bảo trì bo mạch chủ trước khi kiểm tra tham số.',
  },
  {
    id: 'YC-2026-011', donVi: 'DV-004',
    thietBi: 'Trạm phát điện di động UPS-806A phục vụ trạm monitoring — bộ điều tốc',
    maThietBi: 'DTD-PD-367-03',
    mucDich: 'Kiểm tra định kỳ', uuTien: 'trung_binh',
    ngayGui: '2026-03-24', ngayHen: '2026-04-08',
    trangThai: 'moi_tao',
    nguoiGui: 'Hoàng Minh Tuấn',
    phongLab: 'Phòng Lab Điện-Điện tử',
    ghiChu: '',
  },
  {
    id: 'YC-2026-012', donVi: 'DV-006',
    thietBi: 'Trạm monitoring bám sát mục tiêu RSN-75V — khối tạo xung đồng bộ',
    maThietBi: 'DTD-XDB-026-01',
    mucDich: 'Đo kiểm nghiệm thu', uuTien: 'cao',
    ngayGui: '2026-03-25', ngayHen: '2026-04-05',
    trangThai: 'da_tiep_nhan',
    nguoiGui: 'Lê Thanh Tùng',
    phongLab: 'Phòng Lab Tín hiệu - Truyền dẫn',
    ghiChu: 'Nghiệm thu sau nâng cấp lớn, cần đo đầy đủ tham số xung: biên độ, độ rộng, tần số lặp.',
  },
];
